### ISSUE TITLE
[Oracle EF 6.2] System.MissingMethodException 

### ISSUE THREAD

**Issue by dpescatore** [zzzprojects/EntityFramework.DynamicFilters#154]
### Description
Hello. I'm trying to migrate from SQL Server app with EF to an Oracle one. All it's working properly except from a soft delete filter. 
I **created DB from plsql script not migrations** (cannot use them), changed data provider and string connection and tested methods without filters and they work great, except if I add this line of code in OnModelCreating:

`modelBuilder.Filter("IsDeleted", (BaseEntity e) => e.IsDeleted, "N");`

This is the single use of DynamicFilter in the all solution, I hope it would be simple to reproduce.

I'm wondering if someone had the same Issue.

### Exception
I've got the following exception

```
Exception message:
System.MissingMethodException
Stack trace: 
in EntityFramework.DynamicFilters.DynamicFilterConvention.<>c__DisplayClass0_1.<.ctor>b__1(ConventionTypeConfiguration ctc)
 in System.Data.Entity.ModelConfiguration.Conventions.TypeConvention.ApplyCore(Type memberInfo, ModelConfiguration modelConfiguration)
 in System.Data.Entity.ModelConfiguration.Conventions.TypeConventionBase.Apply(Type memberInfo, ModelConfiguration modelConfiguration)
 in System.Data.Entity.ModelConfiguration.Configuration.ConventionsConfiguration.ApplyModelConfiguration(Type type, ModelConfiguration modelConfiguration)
 in System.Data.Entity.ModelConfiguration.Conventions.Convention.ApplyModelConfiguration(Type type, ModelConfiguration modelConfiguration)
 in System.Data.Entity.ModelConfiguration.Configuration.ConventionsConfiguration.ApplyModelConfiguration(Type type, ModelConfiguration modelConfiguration)
 in System.Data.Entity.ModelConfiguration.Mappers.TypeMapper.MapEntityType(Type type)
 in System.Data.Entity.DbModelBuilder.<>c__DisplayClassd.<MapTypes>b__7(Type type)
 in System.Linq.Enumerable.WhereListIterator`1.MoveNext()
 in System.Data.Entity.Utilities.IEnumerableExtensions.Each[T](IEnumerable`1 ts, Action`1 action)
 in System.Data.Entity.DbModelBuilder.MapTypes(EdmModel model)
 in System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
 in System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
 in System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
 in System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
 in System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
 in System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
 in System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
 in System.Data.Entity.Internal.Linq.InternalSet`1.Include(String path)
 in System.Data.Entity.Infrastructure.DbQuery`1.Include(String path)
 in Acme.Users.DataLayer.DAC.EF.Repositories.AcmeRepository.GetUser(String userName) in C:\\[...]\AcmeRepository.cs:row 267"

```

### Further technical details
- EF version: v6.2.0
- EF DynamicFilters version: v3.0.1
- Database Provider: Oracle.ManagedDataAccess.EntityFramework v18.3.0

Any help is apprecciated. 

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @dpescatore ,

A runnable project/solution or Fiddle is now required if you would like we look at it.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._
_You can send it to: info@zzzprojects.com if you need to keep the source private_
Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
