### ISSUE TITLE
Support for EF 6.3 and netstandard

### ISSUE THREAD

**Issue by kosmonavtsv** [zzzprojects/EntityFramework.DynamicFilters#156]

**Comment by JonathanMagnan** [comment]
Thank for reporting,

We will look at it soon.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @kosmonavtsv ,

A new version has been released which should be compatible with EF 6.3,

Could you try it: https://www.nuget.org/packages/EntityFramework.DynamicFilters/3.0.2-preview6-01

If you have any issue, let us know.

**Comment by ismcagdas** [comment]
Hi @JonathanMagnan

Is there any particular reason you have moved to netstandard 2.1 ? When targeting netstandard2.0 in our project, we can't use EntityFramework.DynamicFilters's netstandard 2.1 version and because of that we are not able to support .NET Framework.

For a reference you can check the paragraph starting with "Library authors who need to support .NET Framework" here https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @ismcagdas ,

The only reason we moved to .NET Standard 2.1 is that Entity Framework also has a version with this dependencies.

I believe I'm missing something in this request.

We created a project in .NET Standard 2.0 on our side, we got the following warning:

```txt
Package 'EntityFramework.DynamicFilters 3.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

Which is expected because there is no .NET Standard 2.0 version of our library (only 2.1) but it doesn't have either a version of `Entity Framework` in .NET Standard 2.0

I agree that most library should stick with .NET Standard 2.0 (Even our EF6 fork that support .NET Core is on this version: [EF Classic](https://www.nuget.org/packages/Z.EntityFramework.Classic)). However, the official `Entity Framework` [Nuget Package](https://www.nuget.org/packages/EntityFramework/6.3.0-preview7-19363-02) from Microsoft have a .NET Standard 2.1 dependencies.

So in this case, there is no point to support .NET Standard 2.0?

Let me know what we are missing.

**Comment by ismcagdas** [comment]
@JonathanMagnan thank you for your reply.

> We created a project in .NET Standard 2.0 on our side, we got the following warning:

This was exactly the issue I had. If we just target .NET Standard 2.1, it will only be available for .NET Core 3.0 projects.

After all, instead of targeting .NET Standard 2.0, I targeted both .NET Standard 2.1 and .NET Framework and it seems like it is working for now. I believe you are doing the same.

Thank you for your reply.

**Comment by JonathanMagnan** [comment]
Great,

So everything is fine right?

I must admit that all this .NET Standard/.NET Core thing gets at this moment a lot of people confused included us ;(

If there is anything, let me know.

**Comment by ismcagdas** [comment]
Yes, everything is fine, thank you again for your answer.

> I must admit that all this .NET Standard/.NET Core thing gets at this moment a lot of people confused included us ;(

Absolutely 😄
