### ISSUE TITLE
Context.Set<T>().Find(keyValues) And Use Context.Filter<Interface>() after,

### ISSUE THREAD

**Issue by dragonlus** [zzzprojects/EntityFramework.DynamicFilters#157]
hi Jonathan,
use the Z.EntityFramework.Plus;
l use the interface in filter:
 this.Context.Filter<IClient>("client_id", a => a.Where<IClient>(w => w.client_id == client_id), true);
when the client_id is change , use  Context.Set<T>().Find(keyValues). this function used old client_id.

**Comment by dragonlus** [comment]
I use MiniProfiler trace the sql,like this:
first client_id =1, excute Context.Set<T>.Find("201908021506517490038605f1cc986") the sql is :
 SELECT 
    [Extent1].[modl_id] AS [modl_id], 
    [Extent1].[modl_type] AS [modl_type], 
    [Extent1].[modl_code] AS [modl_code], 
    [Extent1].[modl_name] AS [modl_name], 
    FROM [dbo].[Module] AS [Extent1]
    WHERE  ([Extent1].[client_id] = 1) AND  modl_id='201908021506517490038605f1cc986' 
when I changed  client_id=2 ,excute Context.Set<T>.Find("201908021506517490038605f1cc986")  the sql still is：
 SELECT 
    [Extent1].[modl_id] AS [modl_id], 
    [Extent1].[modl_type] AS [modl_type], 
    [Extent1].[modl_code] AS [modl_code], 
    [Extent1].[modl_name] AS [modl_name], 
    FROM [dbo].[Module] AS [Extent1]
    WHERE  ([Extent1].[client_id] = 1) AND  modl_id='201908021506517490038605f1cc986' 
I excute  Context.Set<T>().take(1).ToList(),the sql is: 
 SELECT 
    [Extent1].[modl_id] AS [modl_id], 
    [Extent1].[modl_type] AS [modl_type], 
    [Extent1].[modl_code] AS [modl_code], 
    [Extent1].[modl_name] AS [modl_name], 
    FROM [dbo].[Module] AS [Extent1]
    WHERE  ([Extent1].[client_id] = 2) AND  modl_id='201908021506517490038605f1cc986' 
why？

**Comment by dragonlus** [comment]
I use  EntityFramework 6.2.0 
Z.EntityFramework.Plus.EF6 1.8.21

**Comment by JonathanMagnan** [comment]
Hello @dragonlus ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
